# ==============================================================================
# PERFIL H2: BANCO DE DADOS SQL EM MEMÓRIA (INICIA SEM PRECISAR DO MYSQL)
# ==============================================================================
spring.datasource.url=jdbc:h2:mem:recargafacil;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração JPA para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o Console H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
